version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notgub-web
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped